### ISSUE TITLE
React Developer Tools

### ISSUE THREAD

**Issue by DaveSimoes** [reactjs/pt-br.react.dev#738]
Olá Folks !!

Poderiam por gentileza confirmar se o tópico "React Developer Tools" foi traduzido ou se encontra com alguém, pois o mesmo se encontra marcado mas não existe o nome de ninguém no momento.

Obrigado.

**Comment by jhonmike** [comment]
Olhando aqui no site https://pt-br.react.dev/learn/react-developer-tools esta traduzido já @DaveSimoes
